[package]
name    = "zona-p2p-overlay"
version = "0.1.0"
edition = "2021"

[dependencies]
zona-p2p-types  = { workspace = true }
zona-p2p-crypto = { workspace = true }
tokio           = { workspace = true }
serde           = { workspace = true }
rand            = { workspace = true }
sha2            = { workspace = true }
tracing         = { workspace = true }
thiserror       = { workspace = true }
