#!/usr/bin/env pwsh
# gen-docker-compose.ps1 -- generate docker-compose.yml for N zona-p2p nodes.
# Usage: ./gen-docker-compose.ps1 [-N <count>] [-OutFile <path>] [-HelloServer] [-ProxyServer] [-DnsServer]

param(
    [int]    $N           = 6,
    [string] $OutFile     = "",
    [switch] $HelloServer = $false,
    [switch] $ProxyServer = $false,
    [switch] $DnsServer   = $false
)

$projectDir = "$PSScriptRoot\..\zona-p2p"
if ($OutFile -eq "") {
    $OutFile = "$projectDir\docker-compose.yml"
}

$baseAdminPort = 17701   # admin HTTP: 17701, 17702, …

$lines = [System.Collections.Generic.List[string]]::new()
$lines.Add("# Auto-generated by gen-docker-compose.ps1 -- do not edit manually.")
$lines.Add("# Run: ./scripts/gen-docker-compose.ps1 -N $N")
$lines.Add("")
$lines.Add("networks:")
$lines.Add("  zona-net:")
$lines.Add("    driver: bridge")
$lines.Add("")
$lines.Add("services:")
$lines.Add("")

for ($i = 0; $i -lt $N; $i++) {
    $hostAdminPort = $baseAdminPort + $i
    $selfUrl       = "http://node${i}:7701"

    # Deterministic seed: repeat index byte 32 times as hex.
    $seedHex = [System.BitConverter]::ToString([byte[]](@($i) * 32)).Replace("-","").ToLower()

    $lines.Add("  node${i}:")
    $lines.Add("    image: zona-p2p")
    $lines.Add("    networks:")
    $lines.Add("      - zona-net")
    $lines.Add("    ports:")
    $lines.Add("      - `"${hostAdminPort}:7701`"")
    $lines.Add("    environment:")
    $lines.Add("      ZONA_NODE_SEED: '${seedHex}'")
    $lines.Add("      ZONA_ADMIN_URL: '${selfUrl}'")
    $lines.Add("      ZONA_ADMIN_PORT: '7701'")

    if ($i -eq 0) {
        $lines.Add("      # node0: seed node, no bootstrap peers")
    } else {
        $lines.Add("      ZONA_BOOTSTRAP_PEERS: 'http://node0:7701'")
    }

    $lines.Add("      RUST_LOG: 'info'")
    $lines.Add("    restart: unless-stopped")
    $lines.Add("")
}

if ($HelloServer) {
    $serverHttpHost = 18800
    # Deterministic seed: all 0xFF bytes
    $serverSeedHex = "ff" * 32

    $lines.Add("  hello-server:")
    $lines.Add("    image: zona-p2p-hello")
    $lines.Add("    networks:")
    $lines.Add("      - zona-net")
    $lines.Add("    ports:")
    $lines.Add("      - `"${serverHttpHost}:8800`"")
    $lines.Add("    environment:")
    $lines.Add("      ZONA_SERVER_SEED: '${serverSeedHex}'")
    $lines.Add("      ZONA_SERVER_SELF_URL: 'http://hello-server:8800'")
    $lines.Add("      ZONA_SERVER_HTTP_ADDR: '0.0.0.0:8800'")
    $lines.Add("      ZONA_SERVER_BOOTSTRAP: 'http://node0:7701'")
    $lines.Add("      RUST_LOG: 'info'")
    $lines.Add("    restart: unless-stopped")
    $lines.Add("    depends_on:")
    $lines.Add("      - node0")
    $lines.Add("")
}

if ($ProxyServer) {
    $proxyHttpHost = 18801
    $lines.Add("  proxy-server:")
    $lines.Add("    image: zona-p2p-proxy")
    $lines.Add("    networks:")
    $lines.Add("      - zona-net")
    $lines.Add("    ports:")
    $lines.Add("      - `"${proxyHttpHost}:8801`"")
    $lines.Add("    environment:")
    $lines.Add("      PROXY_URL: 'http://proxy-server:8801'")
    $lines.Add("      PROXY_LISTEN: '0.0.0.0:8801'")
    $lines.Add("      PROXY_NODES: 'http://node0:7701'")
    $lines.Add("      RUST_LOG: 'info'")
    # Helps when Docker's embedded DNS fails to resolve public hostnames from a container.
    $lines.Add("    dns:")
    $lines.Add("      - 8.8.8.8")
    $lines.Add("      - 8.8.4.4")
    $lines.Add("    restart: unless-stopped")
    $lines.Add("    depends_on:")
    $lines.Add("      - node0")
    $lines.Add("")
}

if ($DnsServer) {
    $dnsHttpHost = 18802
    $lines.Add("  dns-server:")
    $lines.Add("    image: zona-p2p-dns")
    $lines.Add("    networks:")
    $lines.Add("      - zona-net")
    $lines.Add("    ports:")
    $lines.Add("      - `"${dnsHttpHost}:8822`"")
    $lines.Add("    environment:")
    $lines.Add("      ZONA_DNS_URL: 'http://dns-server:8811'")
    $lines.Add("      ZONA_DNS_LISTEN: '0.0.0.0:8811'")
    $lines.Add("      ZONA_DNS_HTTP_LISTEN: '0.0.0.0:8822'")
    $lines.Add("      ZONA_DNS_NODES: 'http://node0:7701'")
    $lines.Add("      ZONA_DNS_ZONES: '/etc/zona/zones.yaml'")
    $lines.Add("      RUST_LOG: 'info'")
    $lines.Add("    volumes:")
    $lines.Add("      - ./zones.docker.yaml:/etc/zona/zones.yaml:ro")
    $lines.Add("    restart: unless-stopped")
    $lines.Add("    depends_on:")
    $lines.Add("      - node0")
    $lines.Add("")
}

[System.IO.File]::WriteAllLines($OutFile, $lines, [System.Text.UTF8Encoding]::new($false))
$extra = @()
if ($HelloServer) { $extra += 'hello-server' }
if ($ProxyServer) { $extra += 'proxy-server' }
if ($DnsServer)   { $extra += 'dns-server' }
$extraStr = if ($extra.Count -gt 0) { ' + ' + ($extra -join ' + ') } else { '' }
Write-Host "Generated: $OutFile  ($N nodes$extraStr)"
Write-Host ""
Write-Host "Admin API URLs (from host):"
for ($i = 0; $i -lt $N; $i++) {
    $port = $baseAdminPort + $i
    Write-Host "  node${i} -> http://localhost:${port}"
}
if ($HelloServer) {
    Write-Host "  hello-server -> http://localhost:${serverHttpHost}/api/packet"
}
if ($ProxyServer) {
    Write-Host "  proxy-server -> http://localhost:18801 (HTTP proxy P2P; use PROXY_NODE_ID from logs)"
}
if ($DnsServer) {
    Write-Host "  dns-server -> http://localhost:18802/api/dns/lookup?domain=... (zones: ./zones.docker.yaml)"
}
