[package]
name    = "zona-p2p-crypto"
version = "0.1.0"
edition = "2021"

[dependencies]
zona-p2p-types  = { workspace = true }
ed25519-dalek   = { workspace = true }
sha2            = { workspace = true }
rand            = { workspace = true }
serde           = { workspace = true }
bincode         = { workspace = true }
thiserror       = { workspace = true }
hex             = { workspace = true }
